/* Auto-generated by tools/gen_background.py - edit that script to change. */
#ifndef BACKGROUND_H
#define BACKGROUND_H

#include <gb/cgb.h>
#include <stdint.h>

#define BACKGROUND_TILE_COUNT    18U
#define BACKGROUND_PALETTE_COUNT 2U
#define BACKGROUND_MAP_WIDTH     32U
#define BACKGROUND_MAP_HEIGHT    18U

extern const palette_color_t background_palettes[8];
extern const uint8_t background_tiles[288];
extern const uint8_t background_map[576];
extern const uint8_t background_attr_map[576];

#endif
