/* Auto-generated by tools/gen_background.py - edit that script to change. */
#ifndef BG_GAMEPLAY_H
#define BG_GAMEPLAY_H

#include <gb/cgb.h>
#include <stdint.h>

#define BG_GAMEPLAY_TILE_COUNT    16U
#define BG_GAMEPLAY_PALETTE_COUNT 2U
#define BG_GAMEPLAY_MAP_WIDTH     48U
#define BG_GAMEPLAY_MAP_HEIGHT    18U

extern const palette_color_t bg_gameplay_palettes[8];
extern const uint8_t bg_gameplay_tiles[256];
extern const uint8_t bg_gameplay_map[864];
extern const uint8_t bg_gameplay_attr_map[864];
#define BG_GAMEPLAY_COLLISION_TILE_COUNT 4U
extern const uint8_t bg_gameplay_collision_tiles[4];
#define BG_GAMEPLAY_SOLID_TILE_COUNT 3U
extern const uint8_t bg_gameplay_solid_tiles[3];

#endif
