/* Auto-generated by tools/gen_background.py - edit that script to change. */
#ifndef BG_GAMEOVER_H
#define BG_GAMEOVER_H

#include <gb/gb.h>
#include <gb/cgb.h>
#include <stdint.h>

#define BG_GAMEOVER_TILE_COUNT    8U
#define BG_GAMEOVER_PALETTE_COUNT 2U
#define BG_GAMEOVER_MAP_WIDTH     20U
#define BG_GAMEOVER_MAP_HEIGHT    18U

BANKREF_EXTERN(bg_gameover_tiles)
extern const palette_color_t bg_gameover_palettes[8];
extern const uint8_t bg_gameover_tiles[128];
extern const uint8_t bg_gameover_map[360];
extern const uint8_t bg_gameover_attr_map[360];

#endif
