/* Auto-generated by tools/gen_background.py - edit that script to change. */
#ifndef BG_WIN_H
#define BG_WIN_H

#include <gb/gb.h>
#include <gb/cgb.h>
#include <stdint.h>

#define BG_WIN_TILE_COUNT    10U
#define BG_WIN_PALETTE_COUNT 2U
#define BG_WIN_MAP_WIDTH     20U
#define BG_WIN_MAP_HEIGHT    18U

BANKREF_EXTERN(bg_win_tiles)
extern const palette_color_t bg_win_palettes[8];
extern const uint8_t bg_win_tiles[160];
extern const uint8_t bg_win_map[360];
extern const uint8_t bg_win_attr_map[360];

#endif
