/* Auto-generated by tools/gen_sprite.py for sprite "enemy". */
#ifndef ENEMY_H
#define ENEMY_H

#include <gb/gb.h>
#include <gb/cgb.h>
#include <stdint.h>

#define ENEMY_TILE_COUNT      8U
#define ENEMY_PALETTE_COUNT    1U
#define ENEMY_TILES_PER_FRAME  2U

/* Animation: idle */
#define ENEMY_ANIM_IDLE_START   0U
#define ENEMY_ANIM_IDLE_FRAMES  2U
#define ENEMY_ANIM_IDLE_SPEED   16U

/* Animation: walk */
#define ENEMY_ANIM_WALK_START   4U
#define ENEMY_ANIM_WALK_FRAMES  2U
#define ENEMY_ANIM_WALK_SPEED   10U

BANKREF_EXTERN(enemy_tiles)
extern const palette_color_t enemy_palettes[4];
extern const uint8_t enemy_tiles[128];

#endif
