/* Auto-generated by tools/gen_sprite.py for sprite "player". */
#ifndef PLAYER_H
#define PLAYER_H

#include <gb/cgb.h>
#include <stdint.h>

#define PLAYER_TILE_COUNT      44U
#define PLAYER_PALETTE_COUNT    1U
#define PLAYER_TILES_PER_FRAME  4U

/* Animation: idle */
#define PLAYER_ANIM_IDLE_START   0U
#define PLAYER_ANIM_IDLE_FRAMES  2U

/* Animation: walk */
#define PLAYER_ANIM_WALK_START   8U
#define PLAYER_ANIM_WALK_FRAMES  4U

/* Animation: jump */
#define PLAYER_ANIM_JUMP_START   24U
#define PLAYER_ANIM_JUMP_FRAMES  2U

/* Animation: die */
#define PLAYER_ANIM_DIE_START   32U
#define PLAYER_ANIM_DIE_FRAMES  3U

extern const palette_color_t player_palettes[4];
extern const uint8_t player_tiles[704];

#endif
